const plants=[
 {name:'Talawade',location:'Pune',unit:'I',area:'40,000',title:'Precision cutting & forming',description:'Large-format laser, plasma and profile cutting, supported by CNC press brake and machining facilities.',image:'cutting',imageAlt:'Plasma and profile cutting machinery at Unit I',machines:['4 kW & 12 kW CNC laser cutting machines','Plasma & profile cutting machine','CNC press brake','5-axis VMC'],metrics:[['300','mm','Profile cutting thickness'],['30','mm','Plasma cutting thickness'],['12','kW','CNC laser power']],dimension:'15,000 × 3,500 mm',dimensionLabel:'Plasma / profile cutting bed',pages:'10–22'},
 {name:'Solu, Alandi',location:'Pune',unit:'II',area:'160,000',title:'Heavy machining & integrated finishing',description:'A broad machining base with robotic welding, shot blasting, painting and stress relieving facilities.',image:'hero',imageAlt:'Heavy horizontal boring machinery at Unit II',machines:['BFW VMC and Makino HMC','Nicolas Correa, PAMA & MAUT horizontal boring machines','Plano milling & vertical turning machines','Robotic welding equipment','Shot blasting, painting & stress relieving facilities'],metrics:[['40','tonnes','Maximum listed crane capacity'],['160,000','sq. ft.','Plant area']],dimension:'Machining · Welding · Finishing',dimensionLabel:'Integrated process capabilities',pages:'23–48'},
 {name:'Chakan, Wasuli',location:'Pune',unit:'III',area:'46,000',title:'Turning, milling & component machining',description:'Vertical turning, machining centres and grinding facilities support a range of component manufacturing requirements.',image:'chakan-vtl',imageAlt:'Vertical turning lathe at Unit III in Chakan',machines:['Vertical turning lathe','COSMOS VMCs & Vulcan 610 VMC','Vertical & horizontal milling machines','Conventional lathes & cylindrical grinding','Plasma, gas & profile cutting equipment'],metrics:[['46,000','sq. ft.','Plant area'],['10','tonnes','Listed operating crane capacity']],dimension:'Turning · Milling · Grinding',dimensionLabel:'Core machining operations',pages:'49–61'},
 {name:'Khandala',location:'Satara',unit:'IV',area:'70,000',title:'Heavy-duty precision machining',description:'Double-column and horizontal machining capabilities, supported by drilling, bending and laser cutting.',image:'machining',imageAlt:'Heavy-duty double-column VMC at Unit IV',machines:['Heavy-duty double-column VMC','4-axis HMC — OKK MCH 800II','Toshiba horizontal machining centre','Radial / portable drilling equipment','Bending machine & 4 kW TRUMPF laser cutting'],metrics:[['32','tonnes','Maximum listed crane capacity'],['4','kW','TRUMPF laser power'],['70,000','sq. ft.','Plant area']],dimension:'VMC · HMC · Laser cutting',dimensionLabel:'Prime manufacturing capabilities',pages:'62–72'}
];
const panel=document.querySelector('#engineering-dashboard');
panel.innerHTML=`<div class="dashboard-heading"><span>PLANT CAPABILITIES / MACHINERY</span><span class="data-dot"></span></div><label class="plant-select-label" for="quality-plant">Select manufacturing plant</label><select id="quality-plant">${plants.map((p,i)=>`<option value="${i}">Unit ${p.unit} — ${p.name}</option>`).join('')}</select><div id="plant-capability" aria-live="polite"></div>`;
function renderPlant(index){const p=plants[index];document.querySelector('#quality-plant').value=String(index);document.querySelector('#plant-capability').innerHTML=`<div class="plant-prime"><span class="meter-kicker">UNIT ${p.unit} / ${p.location.toUpperCase()}</span><h3>${p.title}</h3><p>${p.description}</p></div><div class="plant-machine-photo"><img src="/assets/${p.image}.webp" alt="${p.imageAlt}" loading="lazy"><span>UNIT ${p.unit} · ${p.name.toUpperCase()}</span></div><div class="plant-meters">${p.metrics.map(([value,unit,label])=>`<div><strong>${value}<small>${unit}</small></strong><span>${label}</span></div>`).join('')}</div><button class="machinery-toggle" type="button" aria-expanded="false" aria-controls="machinery-details">Show more</button><div id="machinery-details" hidden><div class="plant-dimension"><span class="dimension-cross" aria-hidden="true">⌖</span><div><strong>${p.dimension}</strong><span>${p.dimensionLabel}</span></div></div><h4 class="machinery-heading">Plant machinery</h4><ul class="plant-machine-list">${p.machines.map(m=>`<li>${m}</li>`).join('')}</ul><p class="data-source">Source: company profile, pages ${p.pages}. Equipment capabilities, not live production readings.</p></div>`;const toggle=document.querySelector(".machinery-toggle");toggle.addEventListener("click",()=>{const expanded=toggle.getAttribute("aria-expanded")==="true";toggle.setAttribute("aria-expanded",String(!expanded));toggle.textContent=expanded?"Show more":"Show less";document.querySelector("#machinery-details").hidden=expanded;});}
renderPlant(0);
document.querySelector('#quality-plant').addEventListener('change',e=>{const index=Number(e.target.value);renderPlant(index);document.querySelector(`[data-unit="${index}"]`).click();});
document.addEventListener('plant-change',e=>renderPlant(e.detail));
